### ISSUE TITLE
Request for build and error output coloring

### ISSUE THREAD

**Issue by jspiro** [kyoh86/richgo#12]
Couldn't live without richgo for our extensive tests. Would love support for build errors (and maybe runtime?) during development, if we compile with richgo.

**Comment by kyoh86** [comment]
I've thought that is good idea, but...

* Build errors are not so typical as test outputs.
    * Processing outputs line-by-line, so `richgo` often misinterprets them.
* Maybe `go build` is less useful than we expected.
    * Major editors tell us build errors automatically and instantly.
        * Coz `go test` sometimes takes too long time, but `go build` is not so.

Although I want to find some way to support it.
