### ISSUE TITLE
Confusing highlighting of test summary

### ISSUE THREAD

**Issue by ghost** [kyoh86/richgo#15]
I find the highlighting of the test summary confusing when there are failures:

Pass:
![image](https://user-images.githubusercontent.com/1039090/27644642-12e55274-5bf2-11e7-8306-7e9031c29f4b.png)

Fail:
![image](https://user-images.githubusercontent.com/1039090/27644743-4896fd8c-5bf2-11e7-9f26-fdd854bf2ace.png)

* Is it possible to use a neutral color for `testing: warning: no tests to run`?
* Sam for `ok       github.com/...    7.186s [no tests to run]`?
* Also for some reason the "Fail" example seems to have 2 spaces after the pipe.

**Comment by kyoh86** [comment]
Sorry for late reply.

I cannot reproduce it.
