### ISSUE TITLE
richgo: command not found error

### ISSUE THREAD

**Issue by patrickandroid** [kyoh86/richgo#16]
Hi I'm seeing the following error after installing richgo:

    $ go get -u github.com/kyoh86/richgo
    $ richgo
    -bash: richgo: command not found

**Comment by kyoh86** [comment]
🤔 hmm...

Please check `echo $PATH` and `ls $(go env GOPATH)/bin | grep richgo`.

i.e.

```
$ echo $PATH
[...]:/Users/kyoh86/go/bin:[...] # "$HOME/go/bin" or "$GOPATH/bin" must be.

$ ls $(go env GOPATH)/bin | grep richgo
richgo # exists.
```

Have you add `$GOPATH/bin` to `$PATH`?
If you have not yet, write a following line in `~/.bashrc`.

```
export PATH=$PATH:$(go env GOPATH)/bin
```

FYR: https://golang.org/doc/code.html#GOPATH

**Comment by kyoh86** [comment]
Note: I'll create a homebrew tap for richgo.

**Comment by kyoh86** [comment]
I've created a new Formula for homebrew. [-> installation](https://github.com/kyoh86/richgo#installation)
So If you use osx and homebrew, try it out.

**Comment by kyoh86** [comment]
@patrickandroid 
I've created a new Formula for homebrew. ->[installation](https://github.com/kyoh86/richgo#installation)
So If you use osx and homebrew, try it out.
