### ISSUE TITLE
Color scheme conflict with gnome solarized dark

### ISSUE THREAD

**Issue by prehistoric-penguin** [kyoh86/richgo#17]
Hi, thanks for your great project.

I found the default color config is conflicted with gnome solarized dark theme, many lines will not show when running test, though they are truly printed on screen(Seems like empty lines). 

Take this as example:
```
START| Persist12C
     | Test (2C): basic persistence ...
     |   ... Passed
PASS | Persist12C (5.77s)
```

These lines can not be seen on the screen

```
START| Persist12C
     | Test (2C): basic persistence ...
     |   ... Passed
```

Only this line can be seen

```
PASS | Persist12C (5.77s)
```

And if I switched into solarized light, everything will be OK.

**Comment by kyoh86** [comment]
:thinking:

The bright-black is used for background color in Solarized dark theme, it's unexpected for me... :weary:

Could you try to put below lines in [.richstyle](https://github.com/kyoh86/richgo#configuration-file-paths) and run `richgo`.
Maybe you can see them all right.

```
startStyle:
  foreground: yellow
```

NOTE: richgo had a bug #18. So please update richgo before trying it out.

**Comment by kyoh86** [comment]
@prehistoric-penguin sorry, I closed this issue by mistake.

**Comment by prehistoric-penguin** [comment]
Got error like this, when following your suggest:

```
error unmarshalling yaml from /home/myname/.richstyle :  yaml: unmarshal errors:
  line 2: cannot unmarshal !!str `yellow` into config.Color
```

**Comment by kyoh86** [comment]
It's known bug(#18) and has already been fixed.
Please update richgo.

```
go get -u github.com/kyoh86/richgo
```

**Comment by prehistoric-penguin** [comment]
Works like a charm, I will adjust the color myself, many thanks!
