### ISSUE TITLE
Highlight coverage

### ISSUE THREAD

**Issue by iwalz** [kyoh86/richgo#2]
Hey,

first of all - cool! After having fancy test outputs for years now, I was a bit bored looking at the go test output - you made my day!

But I think it would be great, if you can somehow highlight the coverage line:
```
     | coverage: 70.2% of statements
```
You can see my output [on this travis run](https://travis-ci.org/iwalz/tdoc/builds/192429305).

I'm executing it like this from a Makefile to get a per-package coverage:
```
test:
	@for pkg in `go list ./...`; do \
		sub_pkg=$$(echo "$$pkg" | cut -d '/' -f 4) ; \
		if [ $$sub_pkg ]; then \
			richgo test -v $$pkg -coverprofile="$$sub_pkg".coverprofile ; \
		fi \
	done
```

Just an idea for an improvement :-)

**Comment by kyoh86** [comment]
@iwalz 

Done.

https://github.com/kyoh86/richgo/releases/tag/v0.2
