### ISSUE TITLE
Testfilter does not work

### ISSUE THREAD

**Issue by sagikazarmark** [kyoh86/richgo#21]
I would like to avoid using richgo as the primary entrypoint for my tests (I have my reasons) so I was happy to see that I can just pass an output to richgo. Unfortunately it doesn't do any colorization.

I tried the following:

```bash
$ go test -v ./pkg/... | tee >(richgo testfilter)
$ go test -v ./pkg/... | richgo testfilter
$ go test -v ./pkg/... | tee >(richgo testfilter) | cat
```

What am doing wrong?

(Note: normally I run a makefile to execute tests, which produces the exact same output as go test, so I doubt it's an issue)

I use macOS with iTerm and zsh

**Comment by sagikazarmark** [comment]
I believe this fixes the problem, not sure about it's correctness though:

```diff
diff --git a/richgo.go b/richgo.go
index 7a4bc22..63a3e05 100644
--- a/richgo.go
+++ b/richgo.go
@@ -41,6 +41,7 @@ func main() {
 		case testFilterCmd:
 			cmd = exec.Command("cat", "-")
 			factory = test.New
+			callTest = true
 		case testCmd:
 			callTest = true
 			fallthrough
```

Also, this could probably be optimized.

**Comment by sagikazarmark** [comment]
Should I provide a PR for this as well?

**Comment by kyoh86** [comment]
@sagikazarmark i fixed it.

**Comment by sagikazarmark** [comment]
Awesome, thanks a lot!
