### ISSUE TITLE
Using richgo as an alias to go no longer works

### ISSUE THREAD

**Issue by sjhandique** [kyoh86/richgo#24]
Prior to Feb 17, 2019, I could use commands like the following after aliasing go with richgo

```
alias go=richgo
go build 
go clean
```

These no longer work and I get the help text for the go CLI instead

I am using go version go1.9 linux/amd64

**Comment by kyoh86** [comment]
I'll rollback tonight (JST)

**Comment by kyoh86** [comment]
sorry, now I rollbacked that to 906501.
re-install richgo by go get -u github.com/kyoh86/richgo
