### ISSUE TITLE
richgo drops the final "FAIL" line from failing tests

### ISSUE THREAD

**Issue by autarch** [kyoh86/richgo#27]
If I run a bunch of tests with `richgo test ./...` and some of the tests in the middle fail but scroll off the screen, I might not notice this. The `go` binary will print a final `FAIL` line by itself when any tests fail, but this gets removed by `richgo`. That means I'm stuck checking `$?` to see if tests failed quickly.

I think a simple fix would be simply put this line back in with the proper coloring.

A _great_ fix would be to instead print a proper test summary showing all the failures by package and test name.

**Comment by kyoh86** [comment]
You can set false to "failPackageStyle.hide" to find them easly.
