### ISSUE TITLE
Proposal: support dual-output mode

### ISSUE THREAD

**Issue by sectioneight** [kyoh86/richgo#3]
Hey there!

This tool is really cool. I'd like to integrate it into my build pipeline, but we currently run go test piped through `go-junit-report` to get test results into jenkins.

If you're open to it, I'd love to contribute a flag that allows outputting both regular and pretty output (either split by STDERR/STDOUT, or make a unix domain socket or temporary file that `go-junit-report` or other tools can use).

Thoughts?

**Comment by kyoh86** [comment]
It sounds good idea!

I think fit to split them with environment variables.

For example:
```
RICHGO_PRETTY_OUTPUT=/dev/stdout
RICHGO_REGULAR_OUTPUT=/dev/null
```

**Comment by sectioneight** [comment]
Cool now that I've got sign off that this is not a completely batty idea, will close this proposal and open up a new PR and Issue describing the proposal.
