### ISSUE TITLE
Colour output not as expected

### ISSUE THREAD

**Issue by Freddixx** [kyoh86/richgo#34]
Hi 👋 

I was playing around with RichGo and am unsure whether this is a bug or not 🤔 

When running a test suite, there seems to be just one single color for all the output in one category. Like in this case everything that belongs to the FAIL category is just plain red:

<img src="https://user-images.githubusercontent.com/1607909/119417377-f9452600-bcf5-11eb-9ae7-b4323a429281.png" height="400" />

The screenshot in your readme suggests that files, line numbers, etc should have a different color. For instance, I would have expected the line indicators to be printed in `magenta` and the actual files in `cyan`.

Am I doing something wrong?

Thank you!

P.S.: I am running richgo on Mac + zsh.

**Comment by kyoh86** [comment]
Give me outputs of "go test".

**Comment by Freddixx** [comment]
Hi @kyoh86, thanks for getting back to me. Here is a screenshot:

<img src="https://user-images.githubusercontent.com/1607909/120623185-ce7a7080-c45f-11eb-8b29-a2696e54f830.png" height="500" />

And here is the raw output:

```
?   	github.com/Freddixx/tmln-backend	[no test files]
--- FAIL: TestBasicAdapter (0.00s)
    adapter_test.go:15: 
        	Error Trace:	adapter_test.go:15
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestBasicAdapter
FAIL
FAIL	github.com/Freddixx/tmln-backend/adapter	0.182s
?   	github.com/Freddixx/tmln-backend/cache	[no test files]
ok  	github.com/Freddixx/tmln-backend/media	(cached)
--- FAIL: TestRSSFetching (0.00s)
    rss_test.go:15: 
        	Error Trace:	rss_test.go:15
        	Error:      	Not equal: 
        	            	expected: "<rss><AnElement>Content</AnElement></rss>"
        	            	actual  : "<rss><AnElement>DifferentContent</AnElement></rss>"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-<rss><AnElement>Content</AnElement></rss>
        	            	+<rss><AnElement>DifferentContent</AnElement></rss>
        	Test:       	TestRSSFetching
    rss_test.go:16: 
        	Error Trace:	rss_test.go:16
        	Error:      	"0" is not greater than or equal to "1"
        	Test:       	TestRSSFetching
    rss_test.go:17: 
        	Error Trace:	rss_test.go:17
        	Error:      	"<rss><AnElement>Content</AnElement></rss>" does not contain "Anelement"
        	Test:       	TestRSSFetching
        	Messages:   	This is failing.
    rss_test.go:18: 
        	Error Trace:	rss_test.go:18
        	Error:      	"<rss><AnElement>Content</AnElement></rss>" does not contain "RSS"
        	Test:       	TestRSSFetching
FAIL
FAIL	github.com/Freddixx/tmln-backend/rss	0.137s
?   	github.com/Freddixx/tmln-backend/sanitise	[no test files]
?   	github.com/Freddixx/tmln-backend/storage	[no test files]
?   	github.com/Freddixx/tmln-backend/story	[no test files]
?   	github.com/Freddixx/tmln-backend/util	[no test files]
FAIL
```

**Comment by kyoh86** [comment]
Thank you for your report, but sorry, it's just that the sample in the readme is too old.
Now `richgo` puts them in the same color for each line.

**Comment by Freddixx** [comment]
Is there any way to bring that back? Because looked really, really good!!!

**Comment by kyoh86** [comment]
I can make them be highlighted, but also the following text in the line lose colors.
For example:
![image](https://user-images.githubusercontent.com/5582459/120677218-cfe48100-c4d1-11eb-9878-a2d769737943.png)
It's due to that the nested highlighting is not supported by ANSI escape characters.

**Comment by kyoh86** [comment]
I got it.
Maybe I can resolve it.

**Comment by kyoh86** [comment]
@Freddixx 
I fixed it.  Please try new version.

**Comment by Freddixx** [comment]
Yep, that worked. Thank you for the fix!
