### ISSUE TITLE
bug: Homebrew: Calling bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by SVilgelm** [kyoh86/richgo#39]
`brew upgrade` repots a warning:
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the kyoh86/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/kyoh86/homebrew-tap/Formula/richgo.rb:9
```

Fix is very trivial, you just need to release new version, `gorelease` already has a fix https://github.com/goreleaser/goreleaser/issues/2595

**Comment by kyoh86** [comment]
:thought_balloon: I'm just confused when people label things as "bug" in a random mood.
Maybe it was a mistake to support homebrew users.

fixed on: https://github.com/kyoh86/homebrew-tap/commit/a1e8ef1c6cb76c38d68760dbb4c1af6dbe134c03

**Comment by SVilgelm** [comment]
maybe it happens because you created issue templates for bugs only?
