### ISSUE TITLE
Is there a way to know richgo version ?

### ISSUE THREAD

**Issue by ccoVeille** [kyoh86/richgo#43]
Hi,

I'm using richgo for a while now, but I'm facing a small issue I would like to raise.

I'm struggling to get the richgo version on the multiple machines I'm using.

So when I doubt if richgo is up-to-date on the machine I am, I'm installing again from latest tag.

Could you consider something to provide the richgo version ?

I don't know why it's not available, may be because richgo is simple a "proxy" to go command, so adding flag may conflict with golang binary.

I'm not talking about having information about richgo with `richgo version` but may be something `richgo --richgo-version`

**Comment by fd0** [comment]
Starting with Go 1.18, this information is embedded in the binary. You can view it with `go version -m`, e.g. for richgo 0.3.10:
```
$ go version -m ./richgo
./richgo: go1.18
	path	github.com/kyoh86/richgo
	mod	github.com/kyoh86/richgo	v0.3.10	h1:iSGvcjhtQN2IVrBDhPk0if0R/RMQnCN1E/9OyAW4UUs=
	[...]
```

**Comment by ccoVeille** [comment]
Thanks a lot, maybe you could add it to the documentation, or is it supposed to be a known thing ?

**Comment by kyoh86** [comment]
done.
