### ISSUE TITLE
Also colorize `go vet ./...`

### ISSUE THREAD

**Issue by fenollp** [kyoh86/richgo#47]
Vet can get pretty verbose with package-prefixed type names as well as file paths.
Colors for file paths, package names and paths would be a great start :)

**Comment by kyoh86** [comment]
Perhaps a method like golangci-lint, which accesses the analyzer directly, would be better for this, rather than an ad hoc and difficult to maintain method like richgo.
And since we already have golangci-lint, I should not bother with this method, which is not precise enough.
