### ISSUE TITLE
Test output whitespace mangled

### ISSUE THREAD

**Issue by atombender** [kyoh86/richgo#5]
Some of our tests output wide columnar diffs when something doesn't match:

```
--- FAIL: TestBuilder (0.01s)
    --- FAIL: TestBuilder/object/nested/deeper (0.01s)
        Error Trace:    diffing.go:48
    			builder_test.go:87
    			builder_test.go:31
    	Error:  	Strings are different (left is expected, right is actual):
    			(logicalplan.Evaluate) {					(logicalplan.Evaluate) {
    			  Expression: (expressions.ObjectTransform) {			  Expression: (expressions.ObjectTransform) {
    			    LHS: (expressions.Placeholder) {				    LHS: (expressions.Placeholder) {
    			      Name: (string) (len=3) "lhs"				      Name: (string) (len=3) "lhs"
    			    },								    },
[...]
```

Here's with `richgo test`:

```
FAIL | Builder (0.02s)
FAIL |       Builder/object/nested/deeper (0.01s)
  Error Trace:  diffing.go:487: 
      builder_test.go:87
      builder_test.go:31
  Error:    Strings are different (left is expected, right is actual):
     |           (logicalplan.Evaluate) {          (logicalplan.Evaluate) {
     |             Expression: (expressions.ObjectTransform) {        Expression: (expressions.ObjectTransform) {
     |               LHS: (expressions.Placeholder) {            LHS: (expressions.Placeholder) {
     |                 Name: (string) (len=3) "lhs"              Name: (string) (len=3) "lhs"
     |               },                    },
```

This is of course completely unreadable.

The lines are aligned with spaces, not tabs, so I don't know why it's compressing them like this.

**Comment by kyoh86** [comment]
I have tried to reproduce that outcome, but I cannot.
Please tell me your environment (OS/shell) and reproducible test code if you don't mind.

**Comment by atombender** [comment]
I was mistaken: The output _is_ aligned with tabs. [Here](https://gist.github.com/atombender/785309884d4f895e63321c6a928db39f) is a test that shows the problem. It applies to `t.Log()`, too.

I also notice that empty lines written to stdout are swallowed entirely. I included an example test that shows this.

**Comment by kyoh86** [comment]
Thanks, I'm looking into it.

**Comment by kyoh86** [comment]
@atombender 
Sorry, I have tried it again, but I cannot reproduce it...

**Comment by atombender** [comment]
[Here](https://github.com/atombender/whitespacetest) is a Docker container you can build to replicate the problem. To run, clone to repo anywhere, then run:

```shell
docker build .
```

On my machine, I get:

![screen shot 2017-02-12 at 12 26 44](https://cloud.githubusercontent.com/assets/50314/22864395/b2a19852-f11e-11e6-9f06-590480f152b7.png)

**Comment by kyoh86** [comment]
@atombender It'll be fixed.

**Comment by atombender** [comment]
Cool, thanks!
